version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/plazapi
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=24h
    depends_on:
      - mongo
    networks:
      - plazapi-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - plazapi-network

networks:
  plazapi-network:
    driver: bridge

volumes:
  mongodb_data:
